/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DraftEvent = TemplateEvent & {
  entity_name: "draft";
  payload: Draft;
};

export interface TemplateEvent {
  operation: "create" | "update" | "delete";
}
export interface Draft {
  address: string[];
  description?: string;
}
